{% set name = "jupyterlab-sos" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:

  url: https://registry.npmjs.org/jupyterlab-sos/-/jupyterlab-sos-{{ version }}.tgz
  sha256: d5799580fbb505f522ff6ba59eadd74efb55810a33c741e75d9e09c0be06c154

build:
  number: 0
  noarch: python

requirements:
  build:
    - nodejs
  host:
    - jupyterlab
    - python >=3.5
  run:
    - jupyterlab
    - nodejs
    - python >=3.5
    - jupyterlab-transient-display-data

test:
  commands:
    - jupyter labextension list | grep jupyterlab-sos  # [unix]
    - jupyter labextension list | findstr jupyterlab-sos  # [win]
    - jupyter lab build

about:
  home: https://github.com/vatlab/jupyterlab-sos
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A JupyterLab extension for SoS Polyglot Notebook and Workflow System
  dev_url: https://github.com/vatlab/jupyterlab-sos

extra:
  recipe-maintainers:
    - BoPeng
