{% set name = "jupyterlab-sos" %}
{% set version = "0.8.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab-sos-{{ version }}.tar.gz
  sha256: 4686768b524fd537e859c632790cb4d79006a5ca48e9fdbaf83cfcb47c9877c3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - nodejs
  host:
    - jupyter-packaging
    - pip
    - python >=3.6
  run:
    - jupyterlab >=3.0.0
    - jupyterlab-transient-display-data
    - nodejs
    - python >=3.6
    - sos

test:
  commands:
    - pip check
  requires:
    - pip
    - sos
    - sos-notebook
    - jupyterlab-transient-display-data

about:
  home: https://github.com/vatlab/jupyterlab-sos
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A JupyterLab extension for SoS Polyglot Notebook and Workflow System
  dev_url: https://github.com/vatlab/jupyterlab-sos

extra:
  recipe-maintainers:
    - BoPeng
