travis:
  secure:
    BINSTAR_TOKEN: Mia99C2/0OAXVITJF21Z4mOA9fSbiRMz+/KXZr5uhuIjZaz5JpXfFj78uk1NiuXi3eOaiUPdWOobiRWS2jFwRJ4WrQSGo3RCVclv5xqvuN48qJc+hLg4S3+C7cTPVTZFbEWJJggDcSwOgrJLRDow3zywtm62uvIRIbwvdhugvpVpemQiyYOrI5g2CIJXd/HWKtiqp2nfUfEp5QpxWs826/H9+4eecOSqhEUH1AQPNYl9DzUjCi/46FoRUBnvWLlGupLUCi+GCQg6HeHtmb6DGVUs/kRtu3Tg4+sRfO/nUrVfkixQqXlpbEFSDXBbEQs7lhHfiwo2xFc6fZWiH70xzTGmY85WErPppCM6v06E6T68OEh8xVNvTF6LXNYR/B2x7Hq5w/P0E0vVF2bKlc+s8/uIHty3IJyH1LCJcBrpjGuBLbid4KiKbYT79xuWtOWU29xFbHLvKsNsUxqHoR5AUDrBztAkrAp7we834d+97roV1Z7Y2jTvDbD88zSPUvZSgN3MDLYM6/l17usTIqiyd7YdwNDJwuacK4eypLqO6goFhqBiuOGN+LQAoTYYiczgOeCvApAbbaW8SHZjo3ZhFls6rk6ii9OKN6wrHKaTG9kkuYo9rCCwKEne51rLsx/+et911ZVmjoHIkhKptEhQlse8m2pBfDj01xX4uCY4FnY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
